### ISSUE TITLE
API calls return an error 401

### ISSUE THREAD

**Issue by kasunsjc** [obs0lete/Get-Weather#3]
I got above error when I try to run the script. but after some time i notice that following has to change as below.

`        $resultsJSON = Invoke-WebRequest "api.openweathermap.org/data/2.5/weather?q=$City,$Country&units=metric&appid=$API&mode=json"
`
We have to remove the **mode=accurate** from the api call

**Comment by obs0lete** [comment]
What City/Country did you use? I'm not able to reproduce the issue you describe.

**Comment by kasunsjc** [comment]
City - Colombo 
Country - LK

**Comment by obs0lete** [comment]
I’m only able to get the 404 if I don’t specify the City and/or Country. 

Did you include the correct parameters when executing this function?

Get-Weather -City Colombo -Country LK

**Comment by kasunsjc** [comment]
Hey It resolved with the **mode=accurate** . I think i Did some mistake in the URL
